import { Router } from 'express';
const router = Router();

import getCharacters from '../controllers/getCharacters.js';
import getCharactersByName from '../controllers/getCharactersByName.js';
import getCharacterById from '../controllers/getCharacterById.js';
import getCharacterByRandomId from '../controllers/getCharacterByRandomId.js';
import getEpisodes from '../controllers/getEpisodes.js';
import getEpisodeById from '../controllers/getEpisodeById.js';
import getUserChange from '../controllers/getUserChange.js';
import getUserData from '../controllers/getUserData.js';
import patchFilterSettings from '../controllers/patchFilterSettings.js';
import patchOptionsSettings from '../controllers/patchOptionsSettings.js';
import patchSearchSettings from '../controllers/patchSearchSettings.js';
import patchUserData from '../controllers/patchUserData.js';
import patchUserSettings from '../controllers/patchUserSettings.js';
import postUser from '../controllers/postUser.js';
import loginUser from '../controllers/loginUser.js';
import changeEmail from '../controllers/changeEmail.js';
import changePassword from '../controllers/changePassword.js';
import getPasswordAuth from '../controllers/getPasswordAuth.js';
import logoutUser from '../controllers/logoutUser.js';
import deleteAccount from '../controllers/deleteAccount.js';

router.get('/characters', getCharacters);
router.get('/characters/query', getCharactersByName);
router.get('/characters/random', getCharacterByRandomId);
router.get('/characters/:id', getCharacterById);
router.get('/episodes', getEpisodes);
router.get('/episodes/:id', getEpisodeById);
router.get('/user/change', getUserChange);
router.get('/userData', getUserData);
router.patch('/filterSettings', patchFilterSettings);
router.patch('/optionsSettings', patchOptionsSettings);
router.patch('/searchSettings', patchSearchSettings);
router.patch('/userData', patchUserData);
router.patch('/userSettings', patchUserSettings);
router.post('/user/changeEmail', changeEmail);
router.post('/user/changePassword', changePassword);
router.post('/user/login', loginUser);
router.post('/user/auth', getPasswordAuth);
router.get('/user/logout', logoutUser);
router.post('/user', postUser);
router.delete('/user', deleteAccount);

export default router;